version: "3"

services:
  vault:
    image: vault:1.13.2
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK

    ports:
      - 8200:8200
